services:
  redis:
    image: redis:7-alpine
    container_name: redis-local-practice
    ports:
      - '6380:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:7
    container_name: mongo-local-practice
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=local_practice_redis
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
